<script lang="ts">
  import { api } from "../lib/api";
  import { modal } from "../lib/modal";
  import type { FolderSummary, ProxyProfile } from "../lib/types";
  let { folders, proxies, onclose, onadded }: { folders: FolderSummary[]; proxies: ProxyProfile[]; onclose: () => void; onadded: () => void } = $props();
  let url = $state(""); let folderId = $state(""); let newFolder = $state(""); let proxyId = $state("direct"); let busy = $state(false); let error = $state(""); let candidates = $state<string[]>([]);
  async function discover() { busy=true;error="";try{candidates=await api.discover(url,proxyId);if(candidates.length===1)url=candidates[0]}catch(e){error=(e as {message:string}).message}finally{busy=false} }
  async function add() { busy=true;error="";try{const target=folderId||undefined;const result=await api.subscribe({url,folderId:newFolder.trim()?undefined:target,proxyProfileId:proxyId});if(newFolder.trim())await api.createFolder(newFolder.trim(),undefined,result.feedId);onadded()}catch(e){error=(e as {message:string}).message}finally{busy=false} }
</script>
<div class="backdrop" role="presentation" onclick={(e)=>e.target===e.currentTarget&&onclose()}><div class="dialog" role="dialog" aria-modal="true" aria-labelledby="add-title" tabindex="-1" use:modal={{onClose:onclose,initialFocus:"input"}}><header><h2 id="add-title">Add subscription</h2><button aria-label="Close add subscription" onclick={onclose}>×</button></header><div class="body"><label>Website or feed URL<input bind:value={url} placeholder="https://example.com/feed.xml" required/></label><div class="row"><label>Existing folder<select bind:value={folderId} disabled={!!newFolder}><option value="">No folder</option>{#each folders as folder}<option value={folder.id}>{folder.name}</option>{/each}</select></label><label>Or create folder<input bind:value={newFolder} placeholder="Folder name"/></label></div><label>Connection<select bind:value={proxyId}>{#each proxies as proxy}<option value={proxy.id}>{proxy.name}</option>{/each}</select></label>{#if candidates.length>1}<label>Discovered feeds<select bind:value={url}>{#each candidates as value}<option>{value}</option>{/each}</select></label>{/if}{#if error}<p class="error" role="alert">{error}</p>{/if}</div><footer><button class="secondary" onclick={discover} disabled={!url||busy} aria-busy={busy}>Discover</button><span></span><button class="secondary" onclick={onclose}>Cancel</button><button class="primary" onclick={add} disabled={!url||busy} aria-busy={busy}>{busy?"Working…":"Subscribe"}</button></footer></div></div>
