<script lang="ts">
  import {api} from "../lib/api";import {modal} from "../lib/modal";import type{FeedSummary,FolderSummary,ProxyProfile}from"../lib/types";
  let{feed,folders,proxies,onclose,onsaved}:{feed:FeedSummary;folders:FolderSummary[];proxies:ProxyProfile[];onclose:()=>void;onsaved:()=>void}=$props();
  let title=$state("");let url=$state("");let folderId=$state("");let proxyId=$state("direct");let interval=$state(60);let blockAds=$state(true);let busy=$state(false);let error=$state("");let confirmingDelete=$state(false);let initialized=false;
  let keepButton=$state<HTMLButtonElement>();
  $effect(()=>{if(!initialized){title=feed.title;url=feed.feedUrl;folderId=feed.folderId??"";proxyId=feed.proxyProfileId??"direct";interval=feed.refreshIntervalMinutes;blockAds=feed.blockAds;initialized=true}});
  $effect(()=>{if(confirmingDelete)queueMicrotask(()=>keepButton?.focus())});
  async function save(){busy=true;try{await api.updateFeed(feed.id,title,url,folderId||undefined,proxyId,interval,blockAds);await onsaved()}catch(e){error=(e as{message:string}).message}finally{busy=false}}
  async function remove(){busy=true;error="";try{await api.deleteFeed(feed.id);await onsaved()}catch(e){error=(e as{message:string}).message}finally{busy=false}}
</script>
<div class="backdrop" role="presentation" onclick={(e)=>e.target===e.currentTarget&&onclose()}><div class="dialog" role="dialog" aria-modal="true" aria-labelledby="feed-title" tabindex="-1" use:modal={{onClose:onclose,initialFocus:"input"}}><header><h2 id="feed-title">Edit subscription</h2><button aria-label="Close edit subscription" onclick={onclose}>×</button></header><div class="body"><label>Title<input bind:value={title} required/></label><label>Feed URL<input bind:value={url} required/></label><div class="row"><label>Folder<select bind:value={folderId}><option value="">No folder</option>{#each folders as f}<option value={f.id}>{f.name}</option>{/each}</select></label><label>Connection<select bind:value={proxyId}>{#each proxies as p}<option value={p.id}>{p.name}</option>{/each}</select></label></div><label>Refresh interval<select bind:value={interval}><option value={15}>15 minutes</option><option value={30}>30 minutes</option><option value={60}>Hourly</option><option value={180}>Every 3 hours</option><option value={720}>Every 12 hours</option><option value={1440}>Daily</option></select></label><label class="check"><input type="checkbox" bind:checked={blockAds}/> Block ads and tracking in article content</label><p class="setting-note">Disabling this affects future refreshes and full-article retrievals; it does not restore content already removed.</p>{#if confirmingDelete}<div class="delete-confirm" role="alert" aria-live="assertive"><div><b>Remove this feed?</b><span>Its locally stored articles will also be removed.</span></div><button class="secondary" bind:this={keepButton} onclick={()=>confirmingDelete=false} disabled={busy}>Keep feed</button><button class="danger solid" onclick={remove} disabled={busy} aria-busy={busy}>{busy?"Removing…":"Remove"}</button></div>{/if}{#if error}<p class="error" role="alert">{error}</p>{/if}</div><footer><button class="danger" onclick={()=>confirmingDelete=true} disabled={busy||confirmingDelete}>Remove feed</button><span></span><button class="secondary" onclick={onclose}>Cancel</button><button class="primary" onclick={save} disabled={busy} aria-busy={busy}>Save</button></footer></div></div>
