<script lang="ts">
  import { onMount } from "svelte";
  import Sidebar from "./components/Sidebar.svelte"; import ArticleList from "./components/ArticleList.svelte"; import Reader from "./components/Reader.svelte";
  import ExternalLinkDialog from "./components/ExternalLinkDialog.svelte";
  import FolderDialog from "./dialogs/FolderDialog.svelte";
  import { api } from "./lib/api";
  import { notifyForRefresh } from "./lib/notifications";
  import { automaticUpdateCheckDue, dismissRelease, dismissedReleaseVersion, markUpdateCheckAttempt, shouldShowRelease } from "./lib/releaseUpdates";
  import type { ArticleDetail, ArticleSummary, ProxyProfile, ReleaseCheck, Scope, SidebarData } from "./lib/types";
  const paneStorageKey="veilfeed.paneWidths";const splitterWidth=7;const defaultSidebarWidth=220;const defaultListWidth=340;
  const emptySidebar:SidebarData={folders:[],feeds:[],allCount:0,unreadCount:0,starredCount:0};
  let sidebar=$state(emptySidebar);let items=$state<ArticleSummary[]>([]);let article=$state<ArticleDetail>();let selectedId=$state<string>();let selection=$state<{scope:Scope;id?:string}>({scope:"all"});let search=$state("");let nextCursor=$state<string>();let listLoading=$state(false);let articleLoading=$state(false);let refreshing=$state(false);let error=$state("");let announcement=$state("");let proxies=$state<ProxyProfile[]>([]);let dialog=$state<"add"|"settings"|"feed"|"folder"|undefined>();let dialogFeedId=$state<string>();let dialogFolderId=$state<string>();let folderAction=$state<"rename"|"delete">();let dialogFolder=$derived(sidebar.folders.find((folder)=>folder.id===dialogFolderId));let articleFeed=$derived(sidebar.feeds.find((feed)=>feed.id===article?.feedId));let DialogComponent=$state<any>();let searchTimer:number;let refreshTimer:number;let articleRequest=0;let articleSelectionRequest=0;
  let viewportWidth=$state(1280);let sidebarWidth=$state(defaultSidebarWidth);let listWidth=$state(defaultListWidth);let drag=$state<{pane:"sidebar"|"list";startX:number;startWidth:number}|undefined>();
  let releaseCheck=$state<ReleaseCheck>();let dismissedVersion=$state(dismissedReleaseVersion());let pendingReleaseUrl=$state<string>();let showReleaseBanner=$derived(shouldShowRelease(releaseCheck,dismissedVersion));
  let paneMins=$derived({sidebar:Math.min(160,Math.max(112,viewportWidth*.2)),list:Math.min(240,Math.max(170,viewportWidth*.27)),reader:Math.min(320,Math.max(220,viewportWidth*.35))});
  let sidebarMax=$derived(Math.max(paneMins.sidebar,viewportWidth-splitterWidth*2-listWidth-paneMins.reader));
  let listMax=$derived(Math.max(paneMins.list,viewportWidth-splitterWidth*2-sidebarWidth-paneMins.reader));
  function clamp(value:number,min:number,max:number){return Math.min(Math.max(value,min),max)}
  function fitPanes(){sidebarWidth=clamp(sidebarWidth,paneMins.sidebar,Math.max(paneMins.sidebar,viewportWidth-splitterWidth*2-paneMins.list-paneMins.reader));listWidth=clamp(listWidth,paneMins.list,Math.max(paneMins.list,viewportWidth-splitterWidth*2-sidebarWidth-paneMins.reader))}
  function savePaneWidths(){globalThis.localStorage?.setItem(paneStorageKey,JSON.stringify({sidebar:Math.round(sidebarWidth),list:Math.round(listWidth)}))}
  function resizePane(pane:"sidebar"|"list",value:number,save=true){if(pane==="sidebar")sidebarWidth=clamp(value,paneMins.sidebar,sidebarMax);else listWidth=clamp(value,paneMins.list,listMax);if(save)savePaneWidths()}
  function startResize(event:PointerEvent,pane:"sidebar"|"list"){if(event.button!==0)return;event.preventDefault();drag={pane,startX:event.clientX,startWidth:pane==="sidebar"?sidebarWidth:listWidth};document.documentElement.dataset.resizing="true"}
  function moveResize(event:PointerEvent){if(!drag)return;resizePane(drag.pane,drag.startWidth+event.clientX-drag.startX,false)}
  function stopResize(){if(!drag)return;drag=undefined;delete document.documentElement.dataset.resizing;savePaneWidths()}
  function resizeKey(event:KeyboardEvent,pane:"sidebar"|"list"){const current=pane==="sidebar"?sidebarWidth:listWidth;const min=pane==="sidebar"?paneMins.sidebar:paneMins.list;const max=pane==="sidebar"?sidebarMax:listMax;let next:number|undefined;if(event.key==="ArrowLeft")next=current-(event.shiftKey?32:8);if(event.key==="ArrowRight")next=current+(event.shiftKey?32:8);if(event.key==="Home")next=min;if(event.key==="End")next=max;if(next===undefined)return;event.preventDefault();resizePane(pane,next)}
  function resetPaneWidths(){sidebarWidth=defaultSidebarWidth;listWidth=defaultListWidth;fitPanes();savePaneWidths()}
  function resizeHandle(node:HTMLElement,pane:"sidebar"|"list"){const pointerdown=(event:PointerEvent)=>startResize(event,pane);const keydown=(event:KeyboardEvent)=>resizeKey(event,pane);node.addEventListener("pointerdown",pointerdown);node.addEventListener("keydown",keydown);node.addEventListener("dblclick",resetPaneWidths);return{destroy(){node.removeEventListener("pointerdown",pointerdown);node.removeEventListener("keydown",keydown);node.removeEventListener("dblclick",resetPaneWidths)}}}
  function query(cursor?:string){return{scope:selection.scope,feedId:selection.scope==="feed"?selection.id:undefined,folderId:selection.scope==="folder"?selection.id:undefined,search:search||undefined,cursor,limit:100}}
  async function loadSidebar(){sidebar=await api.sidebar();proxies=await api.proxies()}
  async function loadArticles(append=false){if(append&&listLoading)return;const request=++articleRequest;const cursor=append?nextCursor:undefined;listLoading=true;error="";try{const page=await api.articles(query(cursor));if(request!==articleRequest)return;items=append?[...items,...page.items]:page.items;nextCursor=page.nextCursor;if(!append)announcement=items.length===1?"1 article loaded":`${items.length} articles loaded`;if(!append&&items.length&&!selectedId)await selectArticle(items[0].id,false)}catch(e){if(request===articleRequest)error=(e as {message:string}).message}finally{if(request===articleRequest)listLoading=false}}
  async function selectArticle(id:string,announce=true){const request=++articleSelectionRequest;selectedId=id;articleLoading=true;try{const loaded=await api.article(id);if(request!==articleSelectionRequest||selectedId!==id)return;article=loaded;const row=items.find(v=>v.id===id);if(row)row.isUnread=false;if(announce)announcement=`Loaded ${article.title}`;await loadSidebar()}catch(e){if(request===articleSelectionRequest)error=(e as {message:string}).message}finally{if(request===articleSelectionRequest)articleLoading=false}}
  async function choose(scope:Scope,id?:string){articleSelectionRequest++;selection={scope,id};selectedId=undefined;article=undefined;articleLoading=false;items=[];nextCursor=undefined;await loadArticles()}
  function doSearch(value:string){search=value;articleRequest++;clearTimeout(searchTimer);searchTimer=window.setTimeout(()=>{items=[];nextCursor=undefined;loadArticles()},220)}
  async function toggleStar(row?:ArticleSummary){const id=row?.id??article?.id;if(!id)return;const value=!(row?.isStarred??article?.isStarred);await api.setArticleState([id],undefined,value);if(row)row.isStarred=value;if(article?.id===id)article.isStarred=value;await loadSidebar()}
  async function markAll(scope:Scope,id?:string){error="";try{await api.markAllRead(scope==="feed"?id:undefined,scope==="folder"?id:undefined,scope);await Promise.all([loadSidebar(),loadArticles()])}catch(e){error=(e as {message:string}).message}}
  async function refresh(feedId?:string){if(refreshing)return;refreshing=true;const feed=feedId?sidebar.feeds.find((item)=>item.id===feedId):undefined;announcement=feed?`Refreshing ${feed.title}`:"Refreshing all feeds";error="";try{const result=await api.refresh(feedId);await notifyForRefresh(result);if(result.errors.length)error=result.errors.join("\n");await Promise.all([loadSidebar(),loadArticles()]);announcement=feed?`Refreshed ${feed.title}`:result.refreshed===1?"Refreshed 1 feed":`Refreshed ${result.refreshed} feeds`}catch(e){error=(e as {message:string}).message}finally{refreshing=false}}
  async function periodicRefresh(){if(refreshing)return;refreshing=true;try{const result=await api.refresh(undefined,true);await notifyForRefresh(result);if(result.refreshed)await Promise.all([loadSidebar(),loadArticles()]);if(result.errors.length)error=result.errors.join("\n")}catch(e){error=(e as {message:string}).message}finally{refreshing=false}}
  async function full(){if(!article)return;article.fullContentHtml=await api.fullContent(article.id)}
  async function openDialog(kind:"add"|"settings"|"feed"|"folder",feedId?:string){dialogFeedId=feedId;if(kind==="folder"){dialogFolderId=undefined;folderAction=undefined;dialog="folder";return}dialog=kind;DialogComponent=(await (kind==="add"?import("./dialogs/AddFeedDialog.svelte"):kind==="settings"?import("./dialogs/SettingsDialog.svelte"):import("./dialogs/FeedDialog.svelte"))).default}
  function manageFolder(folderId:string,action:"rename"|"delete"){dialogFeedId=undefined;dialogFolderId=folderId;folderAction=action;dialog="folder"}
  async function reconcileSelection(){if(selection.scope==="folder"&&!sidebar.folders.some((folder)=>folder.id===selection.id)){selection={scope:"all"};selectedId=undefined;article=undefined;items=[];nextCursor=undefined}}
  async function moveFeed(feedId:string,folderId?:string){if(!feedId)return;error="";try{await api.moveFeed(feedId,folderId);await loadSidebar();await reconcileSelection();await loadArticles()}catch(e){error=(e as {message:string}).message}}
  async function closeAndReload(){dialog=undefined;await loadSidebar();await reconcileSelection();await loadArticles()}
  async function reloadAfterImport(){await loadSidebar();await reconcileSelection();await loadArticles()}
  function keydown(event:KeyboardEvent){const target=event.target as HTMLElement;if(dialog||event.defaultPrevented||event.metaKey||event.ctrlKey||event.altKey||target.closest('input,textarea,select,button,a,[role="menu"],[role="dialog"],[contenteditable="true"]'))return;const index=items.findIndex(v=>v.id===selectedId);if(event.key==="j"||event.key==="ArrowDown"){event.preventDefault();const next=items[Math.min(items.length-1,index+1)];if(next)selectArticle(next.id)}if(event.key==="k"||event.key==="ArrowUp"){event.preventDefault();const previous=items[Math.max(0,index-1)];if(previous)selectArticle(previous.id)}if(event.key==="s")toggleStar();if(event.key==="r")refresh()}
  async function checkUpdates(){markUpdateCheckAttempt();releaseCheck=await api.checkForUpdate();return releaseCheck}
  function updatePreferenceChanged(){if(automaticUpdateCheckDue())void checkUpdates().catch(()=>{})}
  function openRelease(url:string){dialog=undefined;pendingReleaseUrl=url}
  function dismissUpdate(){if(!releaseCheck?.available)return;dismissRelease(releaseCheck.available.version);dismissedVersion=releaseCheck.available.version}
  onMount(()=>{viewportWidth=window.innerWidth;try{const saved=JSON.parse(localStorage.getItem(paneStorageKey)??"null");if(Number.isFinite(saved?.sidebar))sidebarWidth=saved.sidebar;if(Number.isFinite(saved?.list))listWidth=saved.list}catch{}fitPanes();const resize=()=>{viewportWidth=window.innerWidth;fitPanes()};window.addEventListener("keydown",keydown);window.addEventListener("resize",resize);window.addEventListener("pointermove",moveResize);window.addEventListener("pointerup",stopResize);window.addEventListener("pointercancel",stopResize);void (async()=>{try{await loadSidebar();await loadArticles();void refresh();if(automaticUpdateCheckDue())void checkUpdates().catch(()=>{})}catch(e){error=(e as {message:string}).message}})();refreshTimer=window.setInterval(periodicRefresh,60_000);return()=>{window.removeEventListener("keydown",keydown);window.removeEventListener("resize",resize);window.removeEventListener("pointermove",moveResize);window.removeEventListener("pointerup",stopResize);window.removeEventListener("pointercancel",stopResize);delete document.documentElement.dataset.resizing;window.clearInterval(refreshTimer)}});
</script>
<svelte:head><meta name="theme-color" content="#151922"/></svelte:head>
<div class="shell" class:resizing={!!drag} inert={!!dialog||!!pendingReleaseUrl} style={`--sidebar-width:${sidebarWidth}px;--list-width:${listWidth}px`}><Sidebar data={sidebar} {selection} onselect={choose} onadd={()=>openDialog("add")} oncreatefolder={(feedId)=>openDialog("folder",feedId)} onrenamefolder={(id)=>manageFolder(id,"rename")} ondeletefolder={(id)=>manageFolder(id,"delete")} onrefresh={refresh} onsettings={()=>openDialog("settings")} onmove={moveFeed} onmanage={(id)=>openDialog("feed",id)} onmarkread={markAll} {refreshing}/><!-- svelte-ignore a11y_no_noninteractive_tabindex --><div class="pane-splitter" role="separator" aria-label="Resize subscriptions pane" aria-orientation="vertical" aria-valuemin={Math.round(paneMins.sidebar)} aria-valuemax={Math.round(sidebarMax)} aria-valuenow={Math.round(sidebarWidth)} tabindex="0" title="Drag to resize; double-click to reset" use:resizeHandle={"sidebar"}></div><ArticleList {items} feeds={sidebar.feeds} {selectedId} {search} loading={listLoading} hasMore={!!nextCursor} onselect={selectArticle} onsearch={doSearch} onloadmore={()=>loadArticles(true)} ontoggleStar={toggleStar}/><!-- svelte-ignore a11y_no_noninteractive_tabindex --><div class="pane-splitter" role="separator" aria-label="Resize article list pane" aria-orientation="vertical" aria-valuemin={Math.round(paneMins.list)} aria-valuemax={Math.round(listMax)} aria-valuenow={Math.round(listWidth)} tabindex="0" title="Drag to resize; double-click to reset" use:resizeHandle={"list"}></div><Reader {article} feed={articleFeed} loading={articleLoading} onstar={()=>toggleStar()} onfull={full}/></div>
<div class="sr-only" aria-live="polite" aria-atomic="true">{announcement}</div>
{#if error}<div class="toast" role="alert"><span>{error}</span><button aria-label="Dismiss error" onclick={()=>error=""}>×</button></div>{/if}
{#if showReleaseBanner&&releaseCheck?.available}<aside class="update-banner" aria-label="Veilfeed update available"><div><b>{releaseCheck.available.title}</b><span>Version {releaseCheck.available.version} is available.</span></div><button class="primary" onclick={()=>openRelease(releaseCheck!.available!.releaseUrl)}>View release</button><button class="icon-button" aria-label={`Dismiss Veilfeed ${releaseCheck.available.version} update`} onclick={dismissUpdate}>×</button></aside>{/if}
{#if dialog==="folder"}
  {#if !dialogFolderId || dialogFolder}
    <FolderDialog folder={dialogFolder} feeds={sidebar.feeds} initialFeedId={dialogFeedId} initialAction={folderAction} onclose={()=>dialog=undefined} onsaved={closeAndReload} oncreated={closeAndReload}/>
  {/if}
{:else if dialog&&DialogComponent}
  <DialogComponent feed={sidebar.feeds.find((feed)=>feed.id===dialogFeedId)} folders={sidebar.folders} {proxies} {releaseCheck} onclose={()=>dialog=undefined} onadded={closeAndReload} onsaved={closeAndReload} onchanged={loadSidebar} onimported={reloadAfterImport} oncheckupdates={checkUpdates} onopenrelease={openRelease} onupdatepreferencechanged={updatePreferenceChanged}/>
{/if}
{#if pendingReleaseUrl}<ExternalLinkDialog url={pendingReleaseUrl} onclose={()=>pendingReleaseUrl=undefined}/>{/if}
